### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by lapo-luchini** [apache/fluo-bytes#6]
After having read [this article](https://fluo.apache.org/blog/2016/11/10/immutable-bytes/) I was looking for a project that only had that simple dependency and ended up on this project. Is it alive?

Or should I simply extract the [latest `Bytes` from Fluo](https://github.com/mikewalch/fluo/blob/master/modules/api/src/main/java/org/apache/fluo/api/data/Bytes.java) itself?

**Comment by keith-turner** [comment]
I would really like to see a 1.0.0-alpha-1 release of this project made for evaluation, however I have been constantly sidetracked.  

> Or should I simply extract the latest Bytes from Fluo itself?

For internal use within a project I think it would make sense to copy Bytes from Fluo into your code.  If you would like to use it in your project API I think it would be best to have something like this project.  Hopefully this project can get a release out soon. Any help would be welcomed.

**Comment by ctubbsii** [comment]
Hi @lapo-luchini . It's "alive", but stalled due to other priorities. I definitely want to revisit it soon and publish an alpha like @keith-turner suggested.

**Comment by lapo-luchini** [comment]
Okay, I think I'll start by including a copy of that, but hope to convert to this as soon as it's (stable and) on Maven. :)
(might also help a bit, if I end up using it as I suppose I will)

**Comment by ctubbsii** [comment]
@lapo-luchini Help would be awesome, if you have time. Right now, more review/feedback would be great. I'm sure there's more to be done, but I haven't looked at it in awhile.

**Comment by lapo-luchini** [comment]
BTW: in the end I started using it, as compiled from the branch that will be merged with #5.

**Comment by keith-turner** [comment]
@lapo-luchini glad to hear you are using it. Can you share a link to the place where you are using it?

**Comment by lapo-luchini** [comment]
Unfortunately it's in a closed-source work project at @andxor still in the early development process, so no links so far.
